### ISSUE TITLE
 X-Requested-With 已无法获取 HTML

### ISSUE THREAD

**Issue by yzqzss** [Coolapk-UWP/Coolapk-API-Collect#3]
https://github.com/Coolapk-UWP/Coolapk-API-Collect/blob/0ad82afa641fbba46da9845daac29214df96539a/Coolapk-API/HTTP%20%E9%A6%96%E9%83%A8/HTTP%20%E9%A6%96%E9%83%A8.md?plain=1#L12

我在动态的API里试了。`com.coolapk.market` 已经获取不到 HTML 了 ，只能用 `XMLHttpRequest` 获取 JSON。

**Comment by wherewhere** [comment]
因为只有可以返回HTML的才会返回HTML。。。
不然就没客户端什么事了。。。
你试试获取酷安主页

**Comment by yzqzss** [comment]
好的！


~~另外打个广告：~~
```
https://t.me/s/saveweb/35
https://t.me/s/STWP_coolapk_archive/547
```
