### ISSUE TITLE
X-App-Token的算法已经失效了

### ISSUE THREAD

**Issue by CLvax** [Coolapk-UWP/Coolapk-API-Collect#5]
### Describe the bug

用这个算法生产的token去请求api会提示请求不合法

### Steps to reproduce the bug

用这个算法生产的token去请求api会提示请求不合法

### Expected behavior

用这个算法生产的token去请求api会提示请求不合法

### Screenshots

用这个算法生产的token去请求api会提示请求不合法

### Browser

Edge - Edge HTML

### Platform

Linux

**Comment by wherewhere** [comment]
你不会是来钓鱼执法的吧
